#!/usr/bin/env bash
# Builds the vocabulary: every defined term extracted from the normative
# docs into a single generated index (docs/VOCABULARY.md for humans,
# eval/vocabulary.txt for the check). Definitions live in their source
# documents; this index is derived — never edit it by hand.
set -eu

norm() { tr '[:upper:]' '[:lower:]' | sed 's/[[:space:]]\+/ /g; s/^ //; s/ $//'; }
OUT_MD=docs/VOCABULARY.md
OUT_TXT=eval/vocabulary.txt
TMP=$(mktemp)

# 1. Lexicon & list entries across all docs: "- **Term** —"
for f in docs/*.md; do
  grep -nE '^\- \*\*[^*]+\*\*' "$f" 2>/dev/null | while IFS=: read -r ln rest; do
    term=$(echo "$rest" | sed 's/^- \*\*//; s/\*\*.*$//')
    echo -e "$term\t$f:$ln"
  done
done >> "$TMP"

# 1b. Protocol headers: '**P<N> — Name.**'
grep -nE '^\*\*P[0-9]+ — [^*]+\*\*' docs/AGENT-PLATFORM.md | while IFS=: read -r ln rest; do
  term=$(echo "$rest" | sed 's/^\*\*//; s/\*\*.*$//; s/\.$//')
  echo -e "$term\t docs/AGENT-PLATFORM.md:$ln"
done >> "$TMP"

# 2. Charter principles: 'N. **Principle.**'
grep -nE '^[0-9]+\. \*\*' docs/FOUNDING-PRINCIPLES.md | while IFS=: read -r ln rest; do
  term=$(echo "$rest" | sed 's/^[0-9]*\. \*\*//; s/\.\*\*.*$//; s/\*\*.*$//')
  echo -e "$term\t docs/FOUNDING-PRINCIPLES.md:$ln"
done >> "$TMP"

# 3. Ladder/section headings in the platform doc: '## N. Term' / '### Term'
grep -nE '^##+ ' docs/AGENT-PLATFORM.md | while IFS=: read -r ln rest; do
  term=$(echo "$rest" | sed 's/^#\+ //; s/^[0-9]\+\. //')
  echo -e "$term\t docs/AGENT-PLATFORM.md:$ln"
done >> "$TMP"

sort -t$'\t' -k1,1 -u "$TMP" > "${TMP}.sorted"

{
  echo "# Vocabulary (generated index)"
  echo
  echo "Every defined term in the normative corpus, with its defining"
  echo "location. Generated by \`hack/build-vocabulary.sh\` (\`make vocab\`) —"
  echo "do not edit; define terms in their source documents."
  echo
  echo "| Term | Defined at |"
  echo "|---|---|"
  awk -F'\t' '{gsub(/^ +| +$/,"",$2); printf "| %s | `%s` |\n", $1, $2}' "${TMP}.sorted"
} > "$OUT_MD"

cut -f1 "${TMP}.sorted" | norm | sort -u > "$OUT_TXT"
rm -f "$TMP" "${TMP}.sorted"
echo "vocabulary: $(wc -l < "$OUT_TXT") terms -> $OUT_MD, $OUT_TXT"
